version: "3.8"

services:
  web:
    build: .
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql
      - mongodb

  mysql:
    image: mysql:8.2
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vite_et_gourmand
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
